### ISSUE TITLE
Incorrect solar temperature (reading gas temperature value)

### ISSUE THREAD

**Issue by benkemal** [michaelpettorosso/homebridge-connect-my-pool#2]
I have both solar & gas heating, however plugin seems to only read the gas temperature. I rarely use the gas heater so the reading is always reporting incorrect value. Any ideas on how to resolve to get correct reading for solar?

**HomeKit Reading - Solar & Gas both 13 degrees** 
![IMG_1959](https://github.com/michaelpettorosso/homebridge-connect-my-pool/assets/3762346/05ba9fda-9545-4575-b2ca-37ef0ffdc321)

**Actual Solar Reading - 23 degrees**
![IMG_1962](https://github.com/michaelpettorosso/homebridge-connect-my-pool/assets/3762346/f1756d45-47ee-47b8-8d4c-5565eacffea4)

**Actual Gas Reading - 13 degrees**
![IMG_1961](https://github.com/michaelpettorosso/homebridge-connect-my-pool/assets/3762346/65a6db5c-9d0e-441a-a00e-9e3354e36fc3)

**Comment by michaelpettorosso** [comment]
The API that astral provide only gives the pump temperature which for what
I understand is the temperature of the heater side of the system. My
temperatures coincide with this but it looks like your setup maybe
different. My temperature settings come from heater and solar only reflects
actual temperature when running.

**Comment by benkemal** [comment]
Thanks for the quick reply and all your work on this plugin. Looks like API limitation on the Astral side so will close this issue as /api/poolstatus only has one temperature value which appears to come from the gas heater. 

I'll raise feature request with Astral to see if they could expose the pool water temperature reading from the solar heater in the API.
